remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Hi, I'm Pranjal
description: Here is a brief profile of mine.

show_downloads: false